[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_function_tutorial = "3JqxV2WvUeraDrBRx3Da4E2RSiJU654tGcCJcY9Cycey"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
