[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program_deploy = "7chDV64Ry7UhDxtCnX5TD4jYEcRKm4RcKcrNCVw4wUTR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
